# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_src', models.CharField(max_length=200)),
                ('critic', models.CharField(max_length=500)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
